<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE xml>
<project name="Story Graph Tools" default="build">
	<target name="build" depends="clean,javadoc,compile,jar"/>
	<target name="clean">
		<delete dir="doc"/>
		<delete dir="bin"/>
		<mkdir dir="bin"/>
		<delete dir="build"/>
	</target>
    <target name="javadoc">
    	<javadoc
    		doctitle="Story Graph Tools"
    		classpath=".;lib/story-graph/build/jar/sg.jar;lib/sabre/build/jar/sabre.jar"
    		sourcepath="src"
    		destdir="doc"
    		packagenames="
    			edu.uky.cs.nil.sg
    		"
    		access="protected"
    		source="16"
    		use="true"
    		author="true"
    		version="true"
    	/>
    </target>
	<target name="compile">
		<javac
			classpath=".;lib/story-graph/build/jar/sg.jar;lib/sabre/build/jar/sabre.jar"
			srcdir="src"
			destdir="bin"
			includeantruntime="false"
		/>
	</target>
	<target name="jar" depends="sg-gen,sg-explain,sg-rmunx,sg-rmdis,sg-rmunu,sg-rmdup,sg-sort,sg-clean,sg-explore"/>
	<target name="sg-gen">
		<jar destfile="build/jar/sg-gen.jar">
        	<manifest>
        		<attribute name="Main-Class" value="edu.uky.cs.nil.sg.Generate" />
        	</manifest>
        	<fileset dir="src"/>
        	<fileset dir="bin"/>
			<zipgroupfileset dir="." includes="lib/sabre/build/jar/sabre.jar" />
			<zipgroupfileset dir="." includes="lib/story-graph/build/jar/sg.jar" />
        </jar>
    </target>
	<target name="sg-explain">
		<jar destfile="build/jar/sg-explain.jar">
        	<manifest>
        		<attribute name="Main-Class" value="edu.uky.cs.nil.sg.Explain" />
        	</manifest>
        	<fileset dir="src"/>
        	<fileset dir="bin"/>
			<zipgroupfileset dir="." includes="lib/story-graph/build/jar/sg.jar" />
        </jar>
    </target>
	<target name="sg-rmunx">
		<jar destfile="build/jar/sg-rmunx.jar">
        	<manifest>
        		<attribute name="Main-Class" value="edu.uky.cs.nil.sg.RemoveUnexplained" />
        	</manifest>
        	<fileset dir="src"/>
        	<fileset dir="bin"/>
        	<zipgroupfileset dir="." includes="lib/story-graph/build/jar/sg.jar" />
        </jar>
    </target>
	<target name="sg-rmdis">
		<jar destfile="build/jar/sg-rmdis.jar">
        	<manifest>
        		<attribute name="Main-Class" value="edu.uky.cs.nil.sg.RemoveDisconnected" />
        	</manifest>
        	<fileset dir="src"/>
        	<fileset dir="bin"/>
        	<zipgroupfileset dir="." includes="lib/story-graph/build/jar/sg.jar" />
        </jar>
    </target>
	<target name="sg-rmunu">
		<jar destfile="build/jar/sg-rmunu.jar">
        	<manifest>
        		<attribute name="Main-Class" value="edu.uky.cs.nil.sg.RemoveUnused" />
        	</manifest>
        	<fileset dir="src"/>
        	<fileset dir="bin"/>
        	<zipgroupfileset dir="." includes="lib/story-graph/build/jar/sg.jar" />
        </jar>
    </target>
	<target name="sg-rmdup">
		<jar destfile="build/jar/sg-rmdup.jar">
        	<manifest>
        		<attribute name="Main-Class" value="edu.uky.cs.nil.sg.RemoveDuplicates" />
        	</manifest>
        	<fileset dir="src"/>
        	<fileset dir="bin"/>
        	<zipgroupfileset dir="." includes="lib/story-graph/build/jar/sg.jar" />
        </jar>
    </target>
	<target name="sg-sort">
		<jar destfile="build/jar/sg-sort.jar">
        	<manifest>
        		<attribute name="Main-Class" value="edu.uky.cs.nil.sg.Sort" />
        	</manifest>
        	<fileset dir="src"/>
        	<fileset dir="bin"/>
        	<zipgroupfileset dir="." includes="lib/story-graph/build/jar/sg.jar" />
        </jar>
    </target>
	<target name="sg-clean">
		<jar destfile="build/jar/sg-clean.jar">
        	<manifest>
        		<attribute name="Main-Class" value="edu.uky.cs.nil.sg.Clean" />
        	</manifest>
        	<fileset dir="src"/>
        	<fileset dir="bin"/>
        	<zipgroupfileset dir="." includes="lib/story-graph/build/jar/sg.jar" />
        </jar>
    </target>
	<target name="sg-explore">
		<jar destfile="build/jar/sg-explore.jar">
        	<manifest>
        		<attribute name="Main-Class" value="edu.uky.cs.nil.sg.Explore" />
        	</manifest>
        	<fileset dir="src"/>
        	<fileset dir="bin"/>
        	<zipgroupfileset dir="." includes="lib/story-graph/build/jar/sg.jar" />
        </jar>
    </target>
</project>
