<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <!-- Project Meta-Data -->
  <modelVersion>4.0.0</modelVersion>
  <groupId>edu.uky.cs.nil</groupId>
  <artifactId>story-graph-tools</artifactId>
  <version>1.0.1</version>
  <packaging>jar</packaging>
  <name>Story Graph Tools</name>
  <description>Simple command line tools for performing operations on story graphs.</description>
  <url>http://github.com/sgware/story-graph-tools</url>
  <!-- License -->
  <licenses>
    <license>
      <name>GPL-3.0</name>
      <url>http://opensource.org/license/gpl-3.0</url>
    </license>
  </licenses>
  <!-- Developers -->
  <developers>
    <developer>
      <name>Stephen G. Ware</name>
      <email>sgware@cs.uky.edu</email>
    </developer>
  </developers>
  <!-- Source Control -->
  <scm>
    <connection>scm:git:git://github.com/sgware/story-graph-tools.git</connection>
    <developerConnection>scm:git:ssh://github.com:sgware/story-graph-tools.git</developerConnection>
    <url>http://github.com/sgware/story-graph-tools/tree/main</url>
  </scm>
  <!-- Properties -->
  <properties>
    <!-- UTF-8 Encoding -->
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <!-- Use Java 21 -->
    <java.version>21</java.version>
    <maven.compiler.source>21</maven.compiler.source>
    <maven.compiler.target>21</maven.compiler.target>
    <maven.compiler.release>21</maven.compiler.release>
  </properties>
  <!-- Dependencies -->
  <dependencies>
    <dependency>
    <groupId>edu.uky.cs.nil</groupId>
    <artifactId>story-graph</artifactId>
    <version>1.1.0</version>
  </dependency>
  </dependencies>
  <!-- Build -->
  <build>
    <!-- Plugins -->
    <plugins>
      <!-- Delete the docs and build folder during the clean phase. -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-clean-plugin</artifactId>
        <version>3.5.0</version>
        <configuration>
          <filesets>
            <fileset>
              <directory>${basedir}/docs</directory>
              <directory>${basedir}/build</directory>
            </fileset>
          </filesets>
          <force>true</force>
        </configuration>
      </plugin>
      <!-- Generate Javadoc. -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-javadoc-plugin</artifactId>
        <version>3.12.0</version>
        <executions>
          <execution>
            <id>javadoc</id>
            <goals>
              <goal>jar</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <!-- Create a JAR for source files. -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-source-plugin</artifactId>
        <version>3.4.0</version>
        <executions>
          <execution>
            <id>attach-source</id>
            <goals>
              <goal>jar-no-fork</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <!-- Create other JAR files. -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-assembly-plugin</artifactId>
        <version>3.8.0</version>
        <configuration>
          <descriptors>
            <descriptor>src/assembly/jar-all.xml</descriptor>
          </descriptors>
        </configuration>
        <executions>
          <!-- Library JAR that includes compiled, source, and dependencies. -->
          <execution>
            <id>all</id>
            <phase>package</phase>
            <goals>
              <goal>single</goal>
            </goals>
          </execution>
          <!-- Find Explanations Tool -->
          <execution>
            <id>explain</id>
            <phase>package</phase>
            <goals>
              <goal>single</goal>
            </goals>
            <configuration>
              <finalName>sg-explain</finalName>
              <appendAssemblyId>false</appendAssemblyId>
              <attach>false</attach>
              <archive>
                <manifest>
                  <mainClass>edu.uky.cs.nil.sg.ExplainTool</mainClass>
                </manifest>
              </archive>
            </configuration>
          </execution>
          <!-- Remove Unexplained Tool -->
          <execution>
            <id>rmunx</id>
            <phase>package</phase>
            <goals>
              <goal>single</goal>
            </goals>
            <configuration>
              <finalName>sg-rmunx</finalName>
              <appendAssemblyId>false</appendAssemblyId>
              <attach>false</attach>
              <archive>
                <manifest>
                  <mainClass>edu.uky.cs.nil.sg.RemoveUnexplainedTool</mainClass>
                </manifest>
              </archive>
            </configuration>
          </execution>
          <!-- Remove Disconnected Tool -->
          <execution>
            <id>rmdis</id>
            <phase>package</phase>
            <goals>
              <goal>single</goal>
            </goals>
            <configuration>
              <finalName>sg-rmdis</finalName>
              <appendAssemblyId>false</appendAssemblyId>
              <attach>false</attach>
              <archive>
                <manifest>
                  <mainClass>edu.uky.cs.nil.sg.RemoveDisconnectedTool</mainClass>
                </manifest>
              </archive>
            </configuration>
          </execution>
          <!-- Remove Unused Tool -->
          <execution>
            <id>rmunu</id>
            <phase>package</phase>
            <goals>
              <goal>single</goal>
            </goals>
            <configuration>
              <finalName>sg-rmunu</finalName>
              <appendAssemblyId>false</appendAssemblyId>
              <attach>false</attach>
              <archive>
                <manifest>
                  <mainClass>edu.uky.cs.nil.sg.RemoveUnusedTool</mainClass>
                </manifest>
              </archive>
            </configuration>
          </execution>
          <!-- Remove Duplicates Tool -->
          <execution>
            <id>rmdup</id>
            <phase>package</phase>
            <goals>
              <goal>single</goal>
            </goals>
            <configuration>
              <finalName>sg-rmdup</finalName>
              <appendAssemblyId>false</appendAssemblyId>
              <attach>false</attach>
              <archive>
                <manifest>
                  <mainClass>edu.uky.cs.nil.sg.RemoveDuplicatesTool</mainClass>
                </manifest>
              </archive>
            </configuration>
          </execution>
          <!-- Sort Tool -->
          <execution>
            <id>sort</id>
            <phase>package</phase>
            <goals>
              <goal>single</goal>
            </goals>
            <configuration>
              <finalName>sg-sort</finalName>
              <appendAssemblyId>false</appendAssemblyId>
              <attach>false</attach>
              <archive>
                <manifest>
                  <mainClass>edu.uky.cs.nil.sg.SortTool</mainClass>
                </manifest>
              </archive>
            </configuration>
          </execution>
          <!-- Clean Tool -->
          <execution>
            <id>clean</id>
            <phase>package</phase>
            <goals>
              <goal>single</goal>
            </goals>
            <configuration>
              <finalName>sg-clean</finalName>
              <appendAssemblyId>false</appendAssemblyId>
              <attach>false</attach>
              <archive>
                <manifest>
                  <mainClass>edu.uky.cs.nil.sg.CleanTool</mainClass>
                </manifest>
              </archive>
            </configuration>
          </execution>
          <!-- Explore Tool -->
          <execution>
            <id>explore</id>
            <phase>package</phase>
            <goals>
              <goal>single</goal>
            </goals>
            <configuration>
              <finalName>sg-explore</finalName>
              <appendAssemblyId>false</appendAssemblyId>
              <attach>false</attach>
              <archive>
                <manifest>
                  <mainClass>edu.uky.cs.nil.sg.ExploreTool</mainClass>
                </manifest>
              </archive>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <!-- Copy JAR file with source into the build/jar folder. -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <version>3.9.0</version>
        <executions>
          <execution>
            <id>copy-installed</id>
            <phase>install</phase>
            <goals>
              <goal>copy</goal>
            </goals>
            <configuration>
              <artifactItems>
                <artifactItem>
                  <groupId>${project.groupId}</groupId>
                  <artifactId>${project.artifactId}</artifactId>
                  <version>${project.version}</version>
                  <classifier>all</classifier>
                  <type>${project.packaging}</type>
                </artifactItem>
              </artifactItems>
              <outputDirectory>${basedir}/build/jar</outputDirectory>
              <stripVersion>true</stripVersion>
              <stripClassifier>true</stripClassifier>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <!-- Copy Javadoc and tool JARs into other locations. -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-resources-plugin</artifactId>
        <version>3.5.0</version>
        <executions>
          <!-- Copy documentation into the docs folder for GitHub pages. -->
          <execution>
            <id>copy-docs</id>
            <phase>package</phase>
            <goals>
              <goal>copy-resources</goal>
            </goals>
            <configuration>
              <outputDirectory>${basedir}/docs</outputDirectory>
              <resources>
                <resource>
                  <directory>${basedir}/target/reports/apidocs</directory>
                </resource>
              </resources>
            </configuration>
          </execution>
          <!-- Copy tool JAR files into build/jar. -->
          <execution>
            <id>copy-tools</id>
            <phase>package</phase>
            <goals>
              <goal>copy-resources</goal>
            </goals>
            <configuration>
              <outputDirectory>${basedir}/build/jar</outputDirectory>
              <resources>
                <resource>
                  <directory>${basedir}/target</directory>
                  <includes>
                    <include>sg-explain.jar</include>
                    <include>sg-rmunx.jar</include>
                    <include>sg-rmdis.jar</include>
                    <include>sg-rmunu.jar</include>
                    <include>sg-rmdup.jar</include>
                    <include>sg-sort.jar</include>
                    <include>sg-clean.jar</include>
                    <include>sg-explore.jar</include>
                  </includes>
                </resource>
              </resources>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <!-- Generate file checksums -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-gpg-plugin</artifactId>
        <version>3.2.8</version>
        <executions>
          <execution>
            <id>sign-artifacts</id>
            <phase>deploy</phase>
            <goals>
              <goal>sign</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <!-- Publish to the Maven Central Repository -->
      <plugin>
        <groupId>org.sonatype.central</groupId>
        <artifactId>central-publishing-maven-plugin</artifactId>
        <version>0.11.0</version>
        <extensions>true</extensions>
        <configuration>
          <publishingServerId>central</publishingServerId>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>