<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <!-- Project Meta-Data -->
  <modelVersion>4.0.0</modelVersion>
  <groupId>edu.uky.cs.nil</groupId>
  <artifactId>story-graph-tools</artifactId>
  <version>1.0.0</version>
  <packaging>jar</packaging>
  <name>Story Graph Tools</name>
  <description>Simple command line tools for generating, pruning, organizing, and exploring story graphs.</description>
  <url>http://github.com/sgware/story-graph-tools</url>
  <!-- Properties -->
  <properties>
    <!-- UTF-8 Encoding -->
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <!-- Use Java 21 -->
    <java.version>21</java.version>
    <maven.compiler.source>21</maven.compiler.source>
    <maven.compiler.target>21</maven.compiler.target>
    <maven.compiler.release>21</maven.compiler.release>
  </properties>
  <!-- Dependencies -->
  <dependencies>
    <!-- Story Graph Library -->
    <dependency>
      <groupId>edu.uky.cs.nil</groupId>
      <artifactId>story-graph</artifactId>
      <version>1.0.0</version>
    </dependency>
    <!-- Sabre -->
    <dependency>
      <groupId>edu.uky.cs.nil</groupId>
      <artifactId>sabre</artifactId>
      <version>0.8.0</version>
    </dependency>
  </dependencies>
  <!-- Build -->
  <build>
    <!-- Resources -->
    <resources>
      <!-- Include Java source files in JAR file. -->
      <resource>
        <directory>src/main/java</directory>
        <includes>
          <include>**/*.java</include>
        </includes>
      </resource>
    </resources>
    <!-- Plugins -->
    <plugins>
      <!-- Delete files and folders during clean phase. -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-clean-plugin</artifactId>
        <version>3.5.0</version>
        <configuration>
          <filesets>
            <fileset>
              <directory>${basedir}/docs</directory>
            </fileset>
            <fileset>
              <directory>${basedir}/build</directory>
            </fileset>
          </filesets>
          <force>true</force>
        </configuration>
      </plugin>
      <!-- Generate Javadoc. -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-javadoc-plugin</artifactId>
        <version>3.12.0</version>
        <executions>
          <execution>
            <id>javadoc</id>
            <goals>
              <goal>jar</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <!-- Compile each tool as a separate JAR file. -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-assembly-plugin</artifactId>
        <version>3.8.0</version>
        <executions>
          <!-- sg-gen -->
          <execution>
            <id>sg-gen</id>
            <phase>package</phase>
            <goals>
              <goal>single</goal>
            </goals>
            <configuration>
              <archive>
                <manifest>
                  <mainClass>edu.uky.cs.nil.sg.Generate</mainClass>
                </manifest>
              </archive>
              <descriptorRefs>
                <descriptorRef>jar-with-dependencies</descriptorRef>
              </descriptorRefs>
              <finalName>sg-gen</finalName>
              <appendAssemblyId>false</appendAssemblyId>
            </configuration>
          </execution>
          <!-- sg-explain -->
          <execution>
            <id>sg-explain</id>
            <phase>package</phase>
            <goals>
              <goal>single</goal>
            </goals>
            <configuration>
              <archive>
                <manifest>
                  <mainClass>edu.uky.cs.nil.sg.Explain</mainClass>
                </manifest>
              </archive>
              <descriptorRefs>
                <descriptorRef>jar-with-dependencies</descriptorRef>
              </descriptorRefs>
              <finalName>sg-explain</finalName>
              <appendAssemblyId>false</appendAssemblyId>
            </configuration>
          </execution>
          <!-- sg-rmunx -->
          <execution>
            <id>sg-rmunx</id>
            <phase>package</phase>
            <goals>
              <goal>single</goal>
            </goals>
            <configuration>
              <archive>
                <manifest>
                  <mainClass>edu.uky.cs.nil.sg.RemoveUnexplained</mainClass>
                </manifest>
              </archive>
              <descriptorRefs>
                <descriptorRef>jar-with-dependencies</descriptorRef>
              </descriptorRefs>
              <finalName>sg-rmunx</finalName>
              <appendAssemblyId>false</appendAssemblyId>
            </configuration>
          </execution>
          <!-- sg-rmdis -->
          <execution>
            <id>sg-rmdis</id>
            <phase>package</phase>
            <goals>
              <goal>single</goal>
            </goals>
            <configuration>
              <archive>
                <manifest>
                  <mainClass>edu.uky.cs.nil.sg.RemoveDisconnected</mainClass>
                </manifest>
              </archive>
              <descriptorRefs>
                <descriptorRef>jar-with-dependencies</descriptorRef>
              </descriptorRefs>
              <finalName>sg-rmdis</finalName>
              <appendAssemblyId>false</appendAssemblyId>
            </configuration>
          </execution>
          <!-- sg-rmunu -->
          <execution>
            <id>sg-rmunu</id>
            <phase>package</phase>
            <goals>
              <goal>single</goal>
            </goals>
            <configuration>
              <archive>
                <manifest>
                  <mainClass>edu.uky.cs.nil.sg.RemoveUnused</mainClass>
                </manifest>
              </archive>
              <descriptorRefs>
                <descriptorRef>jar-with-dependencies</descriptorRef>
              </descriptorRefs>
              <finalName>sg-rmunu</finalName>
              <appendAssemblyId>false</appendAssemblyId>
            </configuration>
          </execution>
          <!-- sg-rmdup -->
          <execution>
            <id>sg-rmdup</id>
            <phase>package</phase>
            <goals>
              <goal>single</goal>
            </goals>
            <configuration>
              <archive>
                <manifest>
                  <mainClass>edu.uky.cs.nil.sg.RemoveDuplicates</mainClass>
                </manifest>
              </archive>
              <descriptorRefs>
                <descriptorRef>jar-with-dependencies</descriptorRef>
              </descriptorRefs>
              <finalName>sg-rmdup</finalName>
              <appendAssemblyId>false</appendAssemblyId>
            </configuration>
          </execution>
          <!-- sg-sort -->
          <execution>
            <id>sg-sort</id>
            <phase>package</phase>
            <goals>
              <goal>single</goal>
            </goals>
            <configuration>
              <archive>
                <manifest>
                  <mainClass>edu.uky.cs.nil.sg.Sort</mainClass>
                </manifest>
              </archive>
              <descriptorRefs>
                <descriptorRef>jar-with-dependencies</descriptorRef>
              </descriptorRefs>
              <finalName>sg-sort</finalName>
              <appendAssemblyId>false</appendAssemblyId>
            </configuration>
          </execution>
          <!-- sg-clean -->
          <execution>
            <id>sg-clean</id>
            <phase>package</phase>
            <goals>
              <goal>single</goal>
            </goals>
            <configuration>
              <archive>
                <manifest>
                  <mainClass>edu.uky.cs.nil.sg.Clean</mainClass>
                </manifest>
              </archive>
              <descriptorRefs>
                <descriptorRef>jar-with-dependencies</descriptorRef>
              </descriptorRefs>
              <finalName>sg-clean</finalName>
              <appendAssemblyId>false</appendAssemblyId>
            </configuration>
          </execution>
          <!-- sg-explore -->
          <execution>
            <id>sg-explore</id>
            <phase>package</phase>
            <goals>
              <goal>single</goal>
            </goals>
            <configuration>
              <archive>
                <manifest>
                  <mainClass>edu.uky.cs.nil.sg.Explore</mainClass>
                </manifest>
              </archive>
              <descriptorRefs>
                <descriptorRef>jar-with-dependencies</descriptorRef>
              </descriptorRefs>
              <finalName>sg-explore</finalName>
              <appendAssemblyId>false</appendAssemblyId>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <!-- Copy JavaDoc and JAR files into other folders. -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-resources-plugin</artifactId>
        <version>3.5.0</version>
        <executions>
          <!-- Copy JavaDoc into docs -->
          <execution>
            <id>copy-javadoc</id>
            <phase>package</phase>
            <goals>
              <goal>copy-resources</goal>
            </goals>
            <configuration>
              <resources>
                <resource>
                  <directory>target/reports/apidocs</directory>
                </resource>
              </resources>
              <outputDirectory>${basedir}/docs</outputDirectory>
            </configuration>
          </execution>
          <!-- Copy JAR files into biuld/jar -->
          <execution>
            <id>copy-jars</id>
            <phase>package</phase>
            <goals>
              <goal>copy-resources</goal>
            </goals>
            <configuration>
              <resources>
                <resource>
                  <directory>${basedir}/target</directory>
                  <includes>
                    <include>sg-gen.jar</include>
                    <include>sg-explain.jar</include>
                    <include>sg-rmunx.jar</include>
                    <include>sg-rmdis.jar</include>
                    <include>sg-rmunu.jar</include>
                    <include>sg-rmdup.jar</include>
                    <include>sg-sort.jar</include>
                    <include>sg-clean.jar</include>
                    <include>sg-explore.jar</include>
                  </includes>
                </resource>
              </resources>
              <outputDirectory>${basedir}/build/jar</outputDirectory>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>